### PR TITLE
[WIP] Add an API

### PR DESCRIPTION
**Pull request by ur0**
This creates a REST-ful API for Statusify.

@statusify/contributors, please review.

### CODE REVIEW

**Comment by askl56** [comment]
Do you need any help with this?

**Comment by ur0** [comment]
@askl56, could you write tests? I suck at that.

**Comment by askl56** [comment]
Sure but I mainly use RSpec

**Comment by ur0** [comment]
I've been thinking of doing that @askl56. Minitest isn't just that good. If you want, we'll switch to RSpec. It's an awesome idea.

**Comment by askl56** [comment]
Ok, I'll have a look at it tonight.

**Comment by askl56** [comment]
RSpec is far more expressive and basically works as documentation so you can see what the code is meant to do without needing to write additional documentation.

**Comment by ur0** [comment]
Thanks

**Comment by ur0** [comment]
I'm closing this for now - we deviated a lot and this isn't anything close to an RESTful API.

@statusify/contributors I'll cut another branch from master sometime soon. Stay tuned.

**Comment by ur0** [comment]
I'll keep the branch to stick around.

**Pull request closed without merging**
